### ISSUE TITLE
Mobile Matting?

### ISSUE THREAD

**Issue by InternetMaster1** [adumrewal/imageMatting#2]
Is it possible to change the backbone to mobilenetv2 in this library to reduce the size and make it run on mobile devices?

Similar to this library :
https://github.com/foamliu/Mobile-Image-Matting

**Comment by adumrewal** [comment]
Yes, that should be possible. I haven't tested it though.
You can just load the model you want into the final variable and should be good to go.

Something like this:
`
final = DeepLab(backbone='mobilenet', output_stride=16, num_classes=1)
`
