### ISSUE TITLE
Can you provide a demo that any image size can be calculated, not just 320 * 320？

### ISSUE THREAD

**Issue by kaikaigood** [adumrewal/imageMatting#3]
Thank you for your contribution, it's a great work!
I had run the foamliu's repo, but it just could calculate 320*320 size Image. so, can you provide a demo that any image size can be calculated？Thank you again！

**Comment by adumrewal** [comment]
Thank you @kaikaigood !
Yeah, I remember trying to change these image size values. A couple of things to note:
- Only multiples of 64 can be used for image size, this is due the way we create our network.
- I had tried a 960x960 parameter on my system but remember running into memory issues. I have to look into the codes to make memory management more scalable, not sure when will I be able to.

I hope this helps.
